// Generated by gencpp from file real_robot/ControllerMsg.msg
// DO NOT EDIT!


#ifndef REAL_ROBOT_MESSAGE_CONTROLLERMSG_H
#define REAL_ROBOT_MESSAGE_CONTROLLERMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Int32.h>
#include <std_msgs/Int32.h>

namespace real_robot
{
template <class ContainerAllocator>
struct ControllerMsg_
{
  typedef ControllerMsg_<ContainerAllocator> Type;

  ControllerMsg_()
    : header()
    , around()
    , about()  {
    }
  ControllerMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , around(_alloc)
    , about(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Int32_<ContainerAllocator>  _around_type;
  _around_type around;

   typedef  ::std_msgs::Int32_<ContainerAllocator>  _about_type;
  _about_type about;





  typedef boost::shared_ptr< ::real_robot::ControllerMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::real_robot::ControllerMsg_<ContainerAllocator> const> ConstPtr;

}; // struct ControllerMsg_

typedef ::real_robot::ControllerMsg_<std::allocator<void> > ControllerMsg;

typedef boost::shared_ptr< ::real_robot::ControllerMsg > ControllerMsgPtr;
typedef boost::shared_ptr< ::real_robot::ControllerMsg const> ControllerMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::real_robot::ControllerMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::real_robot::ControllerMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::real_robot::ControllerMsg_<ContainerAllocator1> & lhs, const ::real_robot::ControllerMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.around == rhs.around &&
    lhs.about == rhs.about;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::real_robot::ControllerMsg_<ContainerAllocator1> & lhs, const ::real_robot::ControllerMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace real_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::real_robot::ControllerMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::real_robot::ControllerMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::real_robot::ControllerMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::real_robot::ControllerMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::real_robot::ControllerMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::real_robot::ControllerMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::real_robot::ControllerMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d311acc178140cf7a23ce6368d21fe8e";
  }

  static const char* value(const ::real_robot::ControllerMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd311acc178140cf7ULL;
  static const uint64_t static_value2 = 0xa23ce6368d21fe8eULL;
};

template<class ContainerAllocator>
struct DataType< ::real_robot::ControllerMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "real_robot/ControllerMsg";
  }

  static const char* value(const ::real_robot::ControllerMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::real_robot::ControllerMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"std_msgs/Int32 around\n"
"std_msgs/Int32 about\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int32\n"
"int32 data\n"
;
  }

  static const char* value(const ::real_robot::ControllerMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::real_robot::ControllerMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.around);
      stream.next(m.about);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControllerMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::real_robot::ControllerMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::real_robot::ControllerMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "around: ";
    s << std::endl;
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.around);
    s << indent << "about: ";
    s << std::endl;
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.about);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REAL_ROBOT_MESSAGE_CONTROLLERMSG_H
